name: Daily Commit (Invisible)

on:
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Add invisible character to README.md
        run: |
          echo -n "​" >> README.md  # adds zero-width space

      - name: Commit and push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "Azizkhuja"
          git config --global user.email "40321619+Azizkhuja@users.noreply.github.com"
          git add README.md
          git commit -m "Automated daily commit $(date)" || echo "No changes"
          git push
