name: Hourly Commit (Invisible)

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Add invisible empty line to README.md
        run: |
          echo "" >> README.md  # adds a blank line
          # Optional: if you want invisible line instead, use:
          # echo "​" >> README.md

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "Azizkhuja"
          git config --global user.email "40321619+Azizkhuja@users.noreply.github.com"
          git add README.md
          git commit -m "Automated hourly commit $(date)" || echo "No changes to commit"
          git push
